/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_alpha_f_image_CImage
#define _Included_com_alpha_f_image_CImage
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_com_alpha_f_image_CImage_cropCImg
        (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint, jfloat, jfloat, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif